server {
    listen 80;

    # Статична сторінка
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # /api/tasks -> tasks-service:8000/tasks
    location /api/tasks {
        proxy_pass http://tasks-service:8000/tasks;
    }

    # /api/stats -> stats-service:8001/stats
    location /api/stats {
        proxy_pass http://stats-service:8001/stats;
    }
}
